---
- name: Install and configure Nginx web server on Ubuntu
  hosts: ubuntu
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled on boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Confirm Nginx is running
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Check if Nginx is running
      ansible.builtin.shell: systemctl is-active nginx
      register: nginx_status

    - name: Print Nginx status
      ansible.builtin.debug:
        msg: "Nginx is {{ nginx_status.stdout }}"
