---
- name: Create Users & Groups
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Create group
      group:
        name: dev
        state:  present

    - name: Create Users Task
      user:
        name: "{{ item }}"
        state: present
        shell: /bin/bash
        group: dev
      loop:
        - jake
        - tom
        - algreim
     
# - name: Create Users & Groups
#   hosts: amazon-linux
#   remote_user: ec2-user
#   become: yes
#   tasks:
#     - name: Create group
#       group:
#         name: dev
#         state:  present

#     - name: Create Users Task
#       user:
#         name: "{{ item }}"
#         state: present
#         shell: /bin/bash
#         group: dev
#       loop:
#         - jake
#         - tom
#         - algreim